window.PRACTICE_CATEGORIES = [
  {
    id: "word-forms",
    navId: "wordFormsMode",
    icon: "W",
    title: "Word Forms",
    shortTitle: "Word Forms",
    eyebrow: "Articles, gender, plurals, adjectives",
    description: "Train Italian word changes: articles, noun gender, plural forms, adjective agreement, and nationality agreement.",
    exercises: [
      {
        id: "wf-vocab-book",
        category: "word-forms",
        subtype: "Vocabulary recall",
        interaction: "typed",
        prompt: "book",
        answer: "libro",
        acceptedAnswers: ["libro"],
        explanation: "Libro means book. It is masculine: il libro.",
        focusTags: ["vocabulary", "masculine nouns"]
      },
      {
        id: "wf-vocab-city",
        category: "word-forms",
        subtype: "Vocabulary recall",
        interaction: "typed",
        prompt: "city",
        answer: "città",
        acceptedAnswers: ["città"],
        explanation: "Città means city. It is feminine and invariable: la città, le città.",
        focusTags: ["vocabulary", "accented words"]
      },
      {
        id: "wf-article-libro",
        category: "word-forms",
        subtype: "Article + noun choice",
        interaction: "choice",
        prompt: "___ libro",
        options: ["il", "lo", "la", "l’"],
        answer: "il",
        explanation: "Libro is masculine singular and starts with a normal consonant, so use il.",
        focusTags: ["definite articles", "masculine singular"]
      },
      {
        id: "wf-article-studente",
        category: "word-forms",
        subtype: "Article + noun choice",
        interaction: "choice",
        prompt: "___ studente",
        options: ["il", "lo", "la", "l’"],
        answer: "lo",
        explanation: "Studente is masculine singular and starts with s + consonant, so use lo.",
        focusTags: ["definite articles", "s + consonant"]
      },
      {
        id: "wf-article-amica",
        category: "word-forms",
        subtype: "Article + noun choice",
        interaction: "typed",
        prompt: "___ amica",
        answer: "l’",
        acceptedAnswers: ["l’", "l'"],
        explanation: "Amica is feminine singular and starts with a vowel, so la becomes l’. Un’amica uses the apostrophe too.",
        focusTags: ["articles", "apostrophe"]
      },
      {
        id: "wf-gender-penna",
        category: "word-forms",
        subtype: "Gender choice",
        interaction: "choice",
        prompt: "penna",
        options: ["masculine", "feminine"],
        answer: "feminine",
        explanation: "Penna ends in -a and is feminine: la penna.",
        focusTags: ["gender", "nouns"]
      },
      {
        id: "wf-gender-universita",
        category: "word-forms",
        subtype: "Gender choice",
        interaction: "choice",
        prompt: "università",
        options: ["masculine", "feminine"],
        answer: "feminine",
        explanation: "Università is feminine: l’università, le università.",
        focusTags: ["gender", "invariable nouns"]
      },
      {
        id: "wf-plural-libro",
        category: "word-forms",
        subtype: "Singular to plural transformation",
        interaction: "typed",
        prompt: "il libro",
        answer: "i libri",
        acceptedAnswers: ["i libri"],
        explanation: "Masculine nouns ending in -o usually become -i: libro → libri.",
        focusTags: ["plural nouns", "articles"]
      },
      {
        id: "wf-plural-casa",
        category: "word-forms",
        subtype: "Singular to plural transformation",
        interaction: "typed",
        prompt: "la casa",
        answer: "le case",
        acceptedAnswers: ["le case"],
        explanation: "Feminine nouns ending in -a usually become -e: casa → case.",
        focusTags: ["plural nouns", "feminine nouns"]
      },
      {
        id: "wf-plural-studente",
        category: "word-forms",
        subtype: "Singular to plural transformation",
        interaction: "typed",
        prompt: "lo studente",
        answer: "gli studenti",
        acceptedAnswers: ["gli studenti"],
        explanation: "Nouns ending in -e usually become -i. Lo becomes gli in the plural.",
        focusTags: ["plural articles", "nouns ending in -e"]
      },
      {
        id: "wf-plural-amica",
        category: "word-forms",
        subtype: "Singular to plural transformation",
        interaction: "typed",
        prompt: "l’amica",
        answer: "le amiche",
        acceptedAnswers: ["le amiche"],
        explanation: "Amica becomes amiche to keep the hard c sound before e.",
        focusTags: ["plural nouns", "spelling changes"]
      },
      {
        id: "wf-adj-bella",
        category: "word-forms",
        subtype: "Adjective agreement",
        interaction: "typed",
        prompt: "La casa è bell__.",
        answer: "bella",
        acceptedAnswers: ["bella"],
        explanation: "Casa is feminine singular, so bello becomes bella.",
        focusTags: ["adjectives", "feminine singular"]
      },
      {
        id: "wf-adj-nuovi",
        category: "word-forms",
        subtype: "Adjective agreement",
        interaction: "typed",
        prompt: "I libri sono nuov__.",
        answer: "nuovi",
        acceptedAnswers: ["nuovi"],
        explanation: "Libri is masculine plural, so nuovo becomes nuovi.",
        focusTags: ["adjectives", "masculine plural"]
      },
      {
        id: "wf-adj-rosse",
        category: "word-forms",
        subtype: "Adjective agreement",
        interaction: "typed",
        prompt: "Le penne sono ross__.",
        answer: "rosse",
        acceptedAnswers: ["rosse"],
        explanation: "Penne is feminine plural, so rosso becomes rosse.",
        focusTags: ["adjectives", "feminine plural"]
      },
      {
        id: "wf-nationality-italiano",
        category: "word-forms",
        subtype: "Nationality agreement",
        interaction: "typed",
        prompt: "Marco è italian__.",
        answer: "italiano",
        acceptedAnswers: ["italiano"],
        explanation: "Marco is masculine singular, so use italiano.",
        focusTags: ["nationalities", "agreement"]
      },
      {
        id: "wf-nationality-albanese",
        category: "word-forms",
        subtype: "Nationality agreement",
        interaction: "typed",
        prompt: "Anna è albanes__.",
        answer: "albanese",
        acceptedAnswers: ["albanese"],
        explanation: "Albanese ends in -e and is the same for masculine and feminine singular.",
        focusTags: ["nationalities", "-e adjectives"]
      },
      {
        id: "wf-nationality-italiani",
        category: "word-forms",
        subtype: "Nationality agreement",
        interaction: "typed",
        prompt: "Marco e Luca sono italian__.",
        answer: "italiani",
        acceptedAnswers: ["italiani"],
        explanation: "Masculine plural adjectives usually end in -i.",
        focusTags: ["nationalities", "masculine plural"]
      }
    ]
  },
  {
    id: "verb-forms",
    navId: "verbFormsMode",
    icon: "V",
    title: "Verb Forms",
    shortTitle: "Verb Forms",
    eyebrow: "Present tense, reflexives, passato prossimo",
    description: "Practice conjugation, irregular verbs, modal verbs, reflexive forms, auxiliaries, and participle agreement.",
    exercises: [
      {
        id: "vf-essere-io",
        category: "verb-forms",
        subtype: "Pronoun to verb conjugation",
        interaction: "typed",
        prompt: "io + essere",
        answer: "sono",
        acceptedAnswers: ["sono"],
        explanation: "Essere is irregular: io sono.",
        focusTags: ["essere", "present tense"]
      },
      {
        id: "vf-avere-tu",
        category: "verb-forms",
        subtype: "Pronoun to verb conjugation",
        interaction: "typed",
        prompt: "tu + avere",
        answer: "hai",
        acceptedAnswers: ["hai"],
        explanation: "Avere is irregular: tu hai.",
        focusTags: ["avere", "present tense"]
      },
      {
        id: "vf-studiare-noi",
        category: "verb-forms",
        subtype: "Pronoun to verb conjugation",
        interaction: "typed",
        prompt: "noi + studiare",
        answer: "studiamo",
        acceptedAnswers: ["studiamo"],
        explanation: "Regular -are verbs use -iamo with noi.",
        focusTags: ["regular verbs", "noi"]
      },
      {
        id: "vf-reverse-siamo",
        category: "verb-forms",
        subtype: "Reverse conjugation",
        interaction: "choice",
        prompt: "siamo",
        options: ["io", "tu", "noi", "loro"],
        answer: "noi",
        explanation: "Siamo is the noi form of essere.",
        focusTags: ["essere", "subject pronouns"]
      },
      {
        id: "vf-reverse-avete",
        category: "verb-forms",
        subtype: "Reverse conjugation",
        interaction: "choice",
        prompt: "avete",
        options: ["io", "tu", "voi", "loro"],
        answer: "voi",
        explanation: "Avete is the voi form of avere.",
        focusTags: ["avere", "subject pronouns"]
      },
      {
        id: "vf-context-sono",
        category: "verb-forms",
        subtype: "Sentence-context verb choice",
        interaction: "choice",
        prompt: "Io ___ italiano.",
        options: ["sono", "sei", "è", "siamo"],
        answer: "sono",
        explanation: "Io uses sono.",
        focusTags: ["essere", "context"]
      },
      {
        id: "vf-context-hai",
        category: "verb-forms",
        subtype: "Sentence-context verb choice",
        interaction: "choice",
        prompt: "Tu ___ una penna.",
        options: ["ho", "hai", "ha", "hanno"],
        answer: "hai",
        explanation: "Tu uses hai.",
        focusTags: ["avere", "context"]
      },
      {
        id: "vf-context-abita",
        category: "verb-forms",
        subtype: "Sentence-context verb choice",
        interaction: "choice",
        prompt: "Lei ___ a Roma.",
        options: ["abito", "abiti", "abita", "abitano"],
        answer: "abita",
        explanation: "Lei uses the third-person singular form.",
        focusTags: ["regular verbs", "third person"]
      },
      {
        id: "vf-modal-posso",
        category: "verb-forms",
        subtype: "Modal verbs",
        interaction: "choice",
        prompt: "Io ___ parlare italiano.",
        options: ["posso", "puoi", "può", "possiamo"],
        answer: "posso",
        explanation: "Potere: io posso.",
        focusTags: ["potere", "modal verbs"]
      },
      {
        id: "vf-modal-dobbiamo",
        category: "verb-forms",
        subtype: "Modal verbs",
        interaction: "choice",
        prompt: "Noi ___ studiare.",
        options: ["devo", "deve", "dobbiamo", "devono"],
        answer: "dobbiamo",
        explanation: "Dovere: noi dobbiamo.",
        focusTags: ["dovere", "modal verbs"]
      },
      {
        id: "vf-reflexive-svegliarsi",
        category: "verb-forms",
        subtype: "Reflexive verbs",
        interaction: "typed",
        prompt: "io + svegliarsi",
        answer: "mi sveglio",
        acceptedAnswers: ["mi sveglio"],
        explanation: "Svegliarsi is reflexive: io mi sveglio.",
        focusTags: ["reflexive verbs", "daily routine"]
      },
      {
        id: "vf-reflexive-alzarsi",
        category: "verb-forms",
        subtype: "Reflexive verbs",
        interaction: "typed",
        prompt: "tu + alzarsi",
        answer: "ti alzi",
        acceptedAnswers: ["ti alzi"],
        explanation: "Tu uses ti + alzi.",
        focusTags: ["reflexive verbs", "daily routine"]
      },
      {
        id: "vf-reflexive-vestirsi",
        category: "verb-forms",
        subtype: "Reflexive verbs",
        interaction: "typed",
        prompt: "noi + vestirsi",
        answer: "ci vestiamo",
        acceptedAnswers: ["ci vestiamo"],
        explanation: "Noi uses ci + vestiamo.",
        focusTags: ["reflexive verbs", "noi"]
      },
      {
        id: "vf-passato-mangiare",
        category: "verb-forms",
        subtype: "Passato prossimo builder",
        interaction: "typed",
        prompt: "io + mangiare + una pizza",
        answer: "Ho mangiato una pizza.",
        acceptedAnswers: ["Ho mangiato una pizza."],
        explanation: "Mangiare usually uses avere: ho mangiato.",
        focusTags: ["passato prossimo", "avere"]
      },
      {
        id: "vf-passato-andare-male",
        category: "verb-forms",
        subtype: "Passato prossimo builder",
        interaction: "typed",
        prompt: "io + andare + a Roma, male speaker",
        answer: "Sono andato a Roma.",
        acceptedAnswers: ["Sono andato a Roma."],
        explanation: "Andare uses essere. With essere, the participle agrees with the subject: masculine singular = andato.",
        focusTags: ["passato prossimo", "essere", "agreement"]
      },
      {
        id: "vf-passato-andare-female",
        category: "verb-forms",
        subtype: "Passato prossimo builder",
        interaction: "typed",
        prompt: "io + andare + a Roma, female speaker",
        answer: "Sono andata a Roma.",
        acceptedAnswers: ["Sono andata a Roma."],
        explanation: "With essere, the participle agrees with the subject: feminine singular = andata.",
        focusTags: ["passato prossimo", "essere", "agreement"]
      },
      {
        id: "vf-aux-studiare",
        category: "verb-forms",
        subtype: "Auxiliary choice: avere or essere",
        interaction: "choice",
        prompt: "Io ___ studiato italiano.",
        options: ["ho", "sono"],
        answer: "ho",
        explanation: "Studiare uses avere.",
        focusTags: ["auxiliaries", "passato prossimo"]
      },
      {
        id: "vf-aux-uscire",
        category: "verb-forms",
        subtype: "Auxiliary choice: avere or essere",
        interaction: "choice",
        prompt: "Io ___ uscito ieri.",
        options: ["ho", "sono"],
        answer: "sono",
        explanation: "Uscire uses essere in passato prossimo.",
        focusTags: ["auxiliaries", "movement verbs"]
      },
      {
        id: "vf-participle-andata",
        category: "verb-forms",
        subtype: "Past participle agreement",
        interaction: "typed",
        prompt: "Anna è andat__ a casa.",
        answer: "andata",
        acceptedAnswers: ["andata"],
        explanation: "Anna is feminine singular, so use andata.",
        focusTags: ["participle agreement", "essere"]
      },
      {
        id: "vf-participle-usciti",
        category: "verb-forms",
        subtype: "Past participle agreement",
        interaction: "typed",
        prompt: "Marco e Luca sono uscit__.",
        answer: "usciti",
        acceptedAnswers: ["usciti"],
        explanation: "Marco and Luca are masculine plural, so use usciti.",
        focusTags: ["participle agreement", "masculine plural"]
      }
    ]
  },
  {
    id: "sentence-building",
    navId: "sentenceBuildingMode",
    icon: "S",
    title: "Sentence Building",
    shortTitle: "Sentences",
    eyebrow: "Word order, translation, cloze, correction",
    description: "Build full Italian sentences with vocabulary, articles, adjectives, verbs, prepositions, and word order in context.",
    exercises: [
      {
        id: "sb-order-chiamo",
        category: "sentence-building",
        subtype: "Word order puzzle",
        interaction: "word-order",
        prompt: "Arrange the words into a correct sentence.",
        wordBank: ["chiamo", "mi", "Gent"],
        answer: "Mi chiamo Gent.",
        explanation: "The reflexive pronoun mi comes before chiamo.",
        focusTags: ["word order", "reflexive verbs"]
      },
      {
        id: "sb-order-age",
        category: "sentence-building",
        subtype: "Word order puzzle",
        interaction: "word-order",
        prompt: "Arrange the words into a correct sentence.",
        wordBank: ["anni", "ho", "venti"],
        answer: "Ho venti anni.",
        explanation: "Italian uses avere for age: ho venti anni.",
        focusTags: ["word order", "age"]
      },
      {
        id: "sb-order-city",
        category: "sentence-building",
        subtype: "Word order puzzle",
        interaction: "word-order",
        prompt: "Arrange the words into a correct sentence.",
        wordBank: ["a", "abito", "Podgorica"],
        answer: "Abito a Podgorica.",
        explanation: "Use a with cities.",
        focusTags: ["prepositions", "cities"]
      },
      {
        id: "sb-translate-albanian",
        category: "sentence-building",
        subtype: "Sentence translation",
        interaction: "typed",
        prompt: "I am Albanian.",
        answer: "Sono albanese.",
        acceptedAnswers: ["Sono albanese."],
        explanation: "Use essere for nationality.",
        focusTags: ["translation", "nationality"]
      },
      {
        id: "sb-translate-book",
        category: "sentence-building",
        subtype: "Sentence translation",
        interaction: "typed",
        prompt: "I have a book.",
        answer: "Ho un libro.",
        acceptedAnswers: ["Ho un libro."],
        explanation: "Use avere for possession.",
        focusTags: ["translation", "avere"]
      },
      {
        id: "sb-translate-german",
        category: "sentence-building",
        subtype: "Sentence translation",
        interaction: "typed",
        prompt: "She is German.",
        answer: "Lei è tedesca.",
        acceptedAnswers: ["Lei è tedesca.", "È tedesca."],
        explanation: "Tedesca agrees with lei, feminine singular.",
        focusTags: ["translation", "adjective agreement"]
      },
      {
        id: "sb-complete-sono",
        category: "sentence-building",
        subtype: "Sentence completion",
        interaction: "typed",
        prompt: "Mi chiamo Gent. ___ albanese.",
        answer: "Sono",
        acceptedAnswers: ["Sono"],
        explanation: "Use sono for ‘I am’.",
        focusTags: ["sentence completion", "essere"]
      },
      {
        id: "sb-complete-university",
        category: "sentence-building",
        subtype: "Sentence completion",
        interaction: "typed",
        prompt: "Studio italiano ___ università.",
        answer: "all’",
        acceptedAnswers: ["all’", "all'"],
        explanation: "A + l’università becomes all’università.",
        focusTags: ["articulated prepositions", "apostrophe"]
      },
      {
        id: "sb-cloze-intro",
        category: "sentence-building",
        subtype: "Cloze paragraph",
        interaction: "multi-blank",
        prompt: "Mi chiamo Gent. ___ albanese. ___ venti anni. Studio italiano ___ università. Abito ___ Podgorica.",
        answers: ["Sono", "Ho", "all’", "a"],
        acceptedAnswers: [["Sono"], ["Ho"], ["all’", "all'"], ["a"]],
        explanation: "Use sono for nationality, ho for age, all’università for at the university, and a with cities.",
        focusTags: ["cloze", "personal introduction"]
      },
      {
        id: "sb-mixed-station",
        category: "sentence-building",
        subtype: "Mixed grammar context",
        interaction: "multi-blank",
        prompt: "Complete: Ieri Marco ___ andat__ ___ stazione.",
        answers: ["è", "andato", "alla"],
        acceptedAnswers: [["è"], ["andato"], ["alla"]],
        fullAnswer: "Ieri Marco è andato alla stazione.",
        explanation: "Andare uses essere; Marco is masculine singular, so andato; a + la = alla.",
        focusTags: ["passato prossimo", "prepositions", "agreement"]
      },
      {
        id: "sb-error-sono",
        category: "sentence-building",
        subtype: "Error correction",
        interaction: "typed",
        prompt: "Io sei studente.",
        answer: "Io sono studente.",
        acceptedAnswers: ["Io sono studente."],
        explanation: "Io uses sono, not sei.",
        focusTags: ["error correction", "essere"]
      },
      {
        id: "sb-error-libro",
        category: "sentence-building",
        subtype: "Error correction",
        interaction: "typed",
        prompt: "La libro è nuova.",
        answer: "Il libro è nuovo.",
        acceptedAnswers: ["Il libro è nuovo."],
        explanation: "Libro is masculine singular, so use il and nuovo.",
        focusTags: ["error correction", "agreement"]
      },
      {
        id: "sb-error-andato",
        category: "sentence-building",
        subtype: "Error correction",
        interaction: "typed",
        prompt: "Ho andato a casa ieri.",
        answer: "Sono andato a casa ieri.",
        acceptedAnswers: ["Sono andato a casa ieri."],
        explanation: "Andare uses essere in passato prossimo.",
        focusTags: ["error correction", "passato prossimo"]
      }
    ]
  },
  {
    id: "communication-practice",
    navId: "communicationMode",
    icon: "C",
    title: "Communication Practice",
    shortTitle: "Communication",
    eyebrow: "Written exam situations only",
    description: "Practice realistic written A1/A2 situations: introductions, university, bar, directions, hotel, home, routine, family, travel, shopping, and past events.",
    exercises: [
      {
        id: "cp-dialogue-name",
        category: "communication-practice",
        subtype: "Mini dialogues",
        interaction: "typed",
        prompt: "A: Come ti chiami?\nB: Mi ___ Gent.",
        answer: "chiamo",
        acceptedAnswers: ["chiamo"],
        explanation: "Mi chiamo means my name is.",
        focusTags: ["dialogue", "chiamarsi"]
      },
      {
        id: "cp-dialogue-origin",
        category: "communication-practice",
        subtype: "Mini dialogues",
        interaction: "typed",
        prompt: "A: Di dove sei?\nB: ___ albanese.",
        answer: "Sono",
        acceptedAnswers: ["Sono"],
        explanation: "Use sono for nationality.",
        focusTags: ["dialogue", "nationality"]
      },
      {
        id: "cp-dialogue-cost",
        category: "communication-practice",
        subtype: "Mini dialogues",
        interaction: "typed",
        prompt: "A: Quanto costa?\nB: ___ cinque euro.",
        answer: "Costa",
        acceptedAnswers: ["Costa"],
        explanation: "Costa means it costs.",
        focusTags: ["dialogue", "shopping"]
      },
      {
        id: "cp-situation-bar",
        category: "communication-practice",
        subtype: "Situation-based practice",
        interaction: "typed",
        situation: "At a bar",
        prompt: "Write a sentence asking for a coffee.",
        answer: "Vorrei un caffè, per favore.",
        acceptedAnswers: ["Vorrei un caffè, per favore.", "Un caffè, per favore."],
        explanation: "Vorrei is a polite way to say I would like. Un caffè, per favore is also acceptable at a bar.",
        focusTags: ["bar", "polite requests"]
      },
      {
        id: "cp-situation-university",
        category: "communication-practice",
        subtype: "Situation-based practice",
        interaction: "typed",
        situation: "At university",
        prompt: "Write a sentence saying that you study Italian at the university.",
        answer: "Studio italiano all’università.",
        acceptedAnswers: ["Studio italiano all’università.", "Studio l’italiano all’università."],
        explanation: "Use all’università because a + l’università becomes all’università.",
        focusTags: ["university", "articulated prepositions"]
      },
      {
        id: "cp-situation-directions",
        category: "communication-practice",
        subtype: "Situation-based practice",
        interaction: "typed",
        situation: "Asking for directions",
        prompt: "Ask where the station is.",
        answer: "Dov’è la stazione?",
        acceptedAnswers: ["Dov’è la stazione?", "Dove è la stazione?"],
        explanation: "Dov’è means where is. Stazione is feminine: la stazione.",
        focusTags: ["directions", "questions"]
      },
      {
        id: "cp-situation-hotel",
        category: "communication-practice",
        subtype: "Situation-based practice",
        interaction: "typed",
        situation: "Hotel",
        prompt: "Say that you have a reservation.",
        answer: "Ho una prenotazione.",
        acceptedAnswers: ["Ho una prenotazione."],
        explanation: "Use avere for possession: ho una prenotazione.",
        focusTags: ["hotel", "avere"]
      },
      {
        id: "cp-situation-house",
        category: "communication-practice",
        subtype: "Situation-based practice",
        interaction: "typed",
        situation: "Describing your house",
        prompt: "Write a sentence saying your house has two rooms.",
        answer: "La mia casa ha due camere.",
        acceptedAnswers: ["La mia casa ha due camere.", "Casa mia ha due camere."],
        explanation: "Casa is feminine, so use la mia casa. Ha means has.",
        focusTags: ["house", "possession"]
      },
      {
        id: "cp-situation-weather",
        category: "communication-practice",
        subtype: "Situation-based practice",
        interaction: "typed",
        situation: "Weather",
        prompt: "Write that today the weather is beautiful.",
        answer: "Oggi il tempo è bello.",
        acceptedAnswers: ["Oggi il tempo è bello."],
        explanation: "Il tempo means the weather. Bello agrees with tempo, masculine singular.",
        focusTags: ["weather", "adjectives"]
      },
      {
        id: "cp-situation-train",
        category: "communication-practice",
        subtype: "Situation-based practice",
        interaction: "typed",
        situation: "Buying train tickets",
        prompt: "Ask for one ticket to Rome.",
        answer: "Vorrei un biglietto per Roma.",
        acceptedAnswers: ["Vorrei un biglietto per Roma.", "Un biglietto per Roma, per favore."],
        explanation: "Use per before the destination in this ticket request: un biglietto per Roma.",
        focusTags: ["travel", "tickets"]
      },
      {
        id: "cp-situation-clothes",
        category: "communication-practice",
        subtype: "Situation-based practice",
        interaction: "typed",
        situation: "Shopping for clothes",
        prompt: "Ask how much the jacket costs.",
        answer: "Quanto costa la giacca?",
        acceptedAnswers: ["Quanto costa la giacca?"],
        explanation: "Giacca is feminine: la giacca.",
        focusTags: ["shopping", "questions"]
      },
      {
        id: "cp-situation-weekend",
        category: "communication-practice",
        subtype: "Situation-based practice",
        interaction: "typed",
        situation: "Last weekend",
        prompt: "Say that yesterday you studied Italian.",
        answer: "Ieri ho studiato italiano.",
        acceptedAnswers: ["Ieri ho studiato italiano.", "Ho studiato italiano ieri."],
        explanation: "Studiare uses avere in passato prossimo: ho studiato.",
        focusTags: ["past weekend", "passato prossimo"]
      },
      {
        id: "cp-personal-name",
        category: "communication-practice",
        subtype: "Personal answer practice",
        interaction: "typed",
        prompt: "Come ti chiami?",
        answer: "Mi chiamo Gent.",
        acceptedAnswers: ["Mi chiamo Gent."],
        explanation: "Use chiamarsi in the present tense: mi chiamo.",
        focusTags: ["chiamarsi", "present tense"]
      },
      {
        id: "cp-personal-origin",
        category: "communication-practice",
        subtype: "Personal answer practice",
        interaction: "typed",
        prompt: "Di dove sei?",
        answer: "Sono albanese.",
        acceptedAnswers: ["Sono albanese.", "Sono del Montenegro.", "Sono di Podgorica."],
        explanation: "Use essere for nationality or origin: sono albanese, sono del Montenegro, sono di Podgorica.",
        focusTags: ["essere", "nationality", "origin"]
      },
      {
        id: "cp-personal-routine",
        category: "communication-practice",
        subtype: "Personal answer practice",
        interaction: "guided-writing",
        prompt: "Che cosa fai la mattina?",
        modelAnswer: "La mattina mi sveglio alle sette, faccio colazione e studio italiano.",
        requiredAny: [["mi sveglio"], ["faccio colazione"], ["studio", "vado", "esco", "lavoro"]],
        minRequiredMatches: 3,
        explanation: "A strong answer uses daily routine verbs, especially reflexive verbs like mi sveglio.",
        focusTags: ["daily routine", "reflexive verbs"]
      },
      {
        id: "cp-personal-yesterday",
        category: "communication-practice",
        subtype: "Personal answer practice",
        interaction: "guided-writing",
        prompt: "Che cosa hai fatto ieri?",
        modelAnswer: "Ieri ho studiato italiano e sono uscito con amici.",
        requiredAny: [["ieri"], ["ho studiato", "ho mangiato", "ho lavorato"], ["sono uscito", "sono uscita", "sono andato", "sono andata"]],
        minRequiredMatches: 2,
        explanation: "Use passato prossimo for yesterday: ho studiato, sono uscito/a, sono andato/a.",
        focusTags: ["passato prossimo", "past events"]
      },
      {
        id: "cp-guided-routine",
        category: "communication-practice",
        subtype: "Guided writing",
        interaction: "guided-writing",
        prompt: "Write 5 sentences about your daily routine.",
        requiredWords: ["mi sveglio", "faccio colazione", "studio", "pranzo", "vado a letto"],
        minRequiredMatches: 4,
        minSentences: 4,
        modelAnswer: "Mi sveglio alle sette. Faccio colazione. Studio italiano. Pranzo a casa. Vado a letto alle undici.",
        explanation: "Use present-tense routine verbs and include the required daily routine phrases.",
        focusTags: ["guided writing", "daily routine"]
      },
      {
        id: "cp-guided-family",
        category: "communication-practice",
        subtype: "Guided writing",
        interaction: "guided-writing",
        prompt: "Write 5 sentences about your family.",
        requiredWords: ["famiglia", "madre", "padre", "si chiama"],
        requiredAny: [["fratello", "sorella"]],
        minRequiredMatches: 4,
        minSentences: 4,
        modelAnswer: "La mia famiglia è piccola. Mia madre si chiama Ana. Mio padre si chiama Marko. Ho un fratello. Mia sorella è simpatica.",
        explanation: "Use family vocabulary and si chiama to describe names.",
        focusTags: ["guided writing", "family"]
      },
      {
        id: "cp-guided-weekend",
        category: "communication-practice",
        subtype: "Guided writing",
        interaction: "guided-writing",
        prompt: "Write 5 sentences about last weekend using passato prossimo.",
        requiredWords: ["ieri", "ho studiato", "ho mangiato"],
        requiredAny: [["sono uscito", "sono uscita"], ["sono andato", "sono andata"]],
        minRequiredMatches: 4,
        minSentences: 4,
        modelAnswer: "Ieri ho studiato italiano. Ho mangiato una pizza. Sono uscito con amici. Sono andato al centro. Il weekend è stato bello.",
        explanation: "Use passato prossimo and remember agreement with essere: uscito/a, andato/a.",
        focusTags: ["guided writing", "passato prossimo"]
      },
      {
        id: "cp-recall-family",
        category: "communication-practice",
        subtype: "Category recall",
        interaction: "category-recall",
        prompt: "Write 5 family words.",
        acceptedAnswers: ["madre", "padre", "fratello", "sorella", "nonno", "nonna", "zio", "zia", "cugino", "cugina", "figlio", "figlia"],
        requiredCount: 5,
        explanation: "Good family words include madre, padre, fratello, sorella, nonno, nonna, zio, and zia.",
        focusTags: ["category recall", "family"]
      },
      {
        id: "cp-recall-food",
        category: "communication-practice",
        subtype: "Category recall",
        interaction: "category-recall",
        prompt: "Write 5 food/drink words.",
        acceptedAnswers: ["acqua", "caffè", "pizza", "pasta", "panino", "tè", "latte", "vino", "birra", "pane"],
        requiredCount: 5,
        explanation: "Useful food and drink words include acqua, caffè, pizza, pasta, panino, tè, and latte.",
        focusTags: ["category recall", "food"]
      },
      {
        id: "cp-recall-travel",
        category: "communication-practice",
        subtype: "Category recall",
        interaction: "category-recall",
        prompt: "Write 5 transport/travel words.",
        acceptedAnswers: ["treno", "autobus", "biglietto", "stazione", "binario", "aeroporto", "taxi", "valigia", "passaporto"],
        requiredCount: 5,
        explanation: "Transport and travel words include treno, autobus, biglietto, stazione, binario, and aeroporto.",
        focusTags: ["category recall", "travel"]
      }
    ]
  }
];
